site_name: ICPC Menofia

copyright: Copyright &copy; 2025 ICPC Menofia Community

theme:
  name: material
  logo: assets/images/logo-white.jpg
  favicon: assets/images/logo-white.jpg

  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - navigation.indexes

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: red
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: yellow

  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ICPC-Menofia
      name: GitHub
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ICPCMNF
      name: Facebook Page
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bdKQ3RSSxK
      name: Discord Community
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/icpcmenofia
      name: X (Twitter)
    - icon: fontawesome/solid/code
      link: https://codeforces.com/profile/ICPC_Menofia
      name: Codeforces Profile

extra_css:
  - assets/css/custom.css

nav:
  - Home: index.md
  - Community:
      - Overview: community/index.md
      - About Us: community/about_us.md
      - Our Coaches: community/coaches.md
      - Join Our Community: community/join_us.md
  - Training:
      - Overview: training/index.md
      - Newcomer Training: training/plan/Newcommer_training.md
      - Level 1 Training: training/plan/Level1_training.md
      - Level 2 Training: training/plan/Level2_training.md
      - Senior Training: training/plan/Senior_training.md
      - 2024 Training:
        - Level 2 Training: training/2024/level2_training.md
  - Resources:
      - Overview: resources/index.md
      - Sessions Archive: resources/sessions/index.md
      - FAQ: resources/FAQ.md
  - News:
      - Overview: news/index.md
      - 2025 Events: news/2025_events.md
      - 2024 Events: news/2024_events.md
      - 2023 Events: news/2023_events.md
      - 2022 Events: news/2022_events.md
      - 2021 Events: news/2021_events.md
      - 2020 Events: news/2020_events.md

plugins:
  - search:
      lang: en

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
